from .finance import FINANCE_FIELD_KEYS, FINANCE_SCHEMA
from .manufacturing import MANUFACTURING_FIELD_KEYS, MANUFACTURING_SCHEMA
from .pharma import PHARMA_FIELD_KEYS, PHARMA_SCHEMA


INDUSTRY_SCHEMA_MAP = {
    "pharma": PHARMA_SCHEMA,
    "finance": FINANCE_SCHEMA,
    "manufacturing": MANUFACTURING_SCHEMA,
}

INDUSTRY_FIELD_KEYS_MAP = {
    "pharma": PHARMA_FIELD_KEYS,
    "finance": FINANCE_FIELD_KEYS,
    "manufacturing": MANUFACTURING_FIELD_KEYS,
}


__all__ = [
    "FINANCE_FIELD_KEYS",
    "FINANCE_SCHEMA",
    "INDUSTRY_FIELD_KEYS_MAP",
    "INDUSTRY_SCHEMA_MAP",
    "MANUFACTURING_FIELD_KEYS",
    "MANUFACTURING_SCHEMA",
    "PHARMA_FIELD_KEYS",
    "PHARMA_SCHEMA",
]
