from typing import Any, Dict, List


def q_field(
    field_key: str,
    name_cn: str,
    category: str,
    value_type: str,
    unit_type: str,
    aliases: List[str],
    required_any: List[str] | None = None,
    forbidden_any: List[str] | None = None,
    unit_examples: List[str] | None = None,
    preferred_source: str = "appendix_table",
    unit_required: bool = True,
    year_required: bool = True,
) -> Dict[str, Any]:
    return {
        "field_key": field_key,
        "name_cn": name_cn,
        "category": category,
        "indicator_type": "quantitative",
        "value_type": value_type,
        "preferred_source": preferred_source,
        "unit_required": unit_required,
        "year_required": year_required,
        "unit_type": unit_type,
        "unit_examples": unit_examples or [],
        "aliases": aliases,
        "required_any": required_any if required_any is not None else aliases,
        "forbidden_any": forbidden_any or [],
    }


E_SCHEMA_DATA = [
    q_field(
        "total_ghg_emissions",
        "温室气体排放总量",
        "E",
        "number",
        "ghg",
        aliases=["温室气体排放总量", "温室气体排放总计", "碳排放总量", "GHG排放总量"],
        forbidden_any=["范围一", "范围1", "Scope 1", "范围二", "范围2", "Scope 2", "范围三", "范围3", "Scope 3", "强度"],
        unit_examples=["吨CO2e", "吨二氧化碳当量", "二氧化碳当量公吨数", "tCO2e"],
    ),
    q_field(
        "ghg_emissions_intensity",
        "温室气体排放强度",
        "E",
        "number",
        "intensity",
        aliases=["温室气体排放强度", "温室气体排放密度", "碳排放强度", "碳排放密度", "GHG排放强度", "单位营收温室气体排放", "单位收入温室气体排放"],
        required_any=["强度", "密度", "单位营收", "单位收入"],
        forbidden_any=["总量", "范围一", "范围1", "Scope 1", "范围二", "范围2", "Scope 2"],
        unit_examples=["吨CO2e/万元", "吨二氧化碳当量/万元", "tCO2e/百万元"],
    ),
    q_field(
        "scope_1_emissions",
        "范围一温室气体排放量",
        "E",
        "number",
        "ghg",
        aliases=["范围一温室气体排放量", "范围1温室气体排放量", "Scope 1排放", "直接温室气体排放"],
        required_any=["范围一", "范围1", "Scope 1", "直接温室气体"],
        forbidden_any=["范围二", "范围2", "Scope 2", "范围三", "范围3", "Scope 3"],
        unit_examples=["吨CO2e", "吨二氧化碳当量", "二氧化碳当量公吨数", "tCO2e"],
    ),
    q_field(
        "scope_2_emissions",
        "范围二温室气体排放量",
        "E",
        "number",
        "ghg",
        aliases=["范围二温室气体排放量", "范围2温室气体排放量", "Scope 2排放", "间接温室气体排放"],
        required_any=["范围二", "范围2", "Scope 2", "间接温室气体"],
        forbidden_any=["范围一", "范围1", "Scope 1", "范围三", "范围3", "Scope 3"],
        unit_examples=["吨CO2e", "吨二氧化碳当量", "二氧化碳当量公吨数", "tCO2e"],
    ),
    q_field(
        "energy_consumption_total",
        "能源消耗总量",
        "E",
        "number",
        "energy",
        aliases=["能源消耗总量", "综合能源消耗", "能源使用总量", "直接能源消耗"],
        forbidden_any=["强度", "密度", "单位产值"],
        unit_examples=["兆瓦时", "MWh", "千瓦时", "吨标准煤"],
    ),
    q_field(
        "energy_consumption_intensity",
        "能源消耗强度",
        "E",
        "number",
        "intensity",
        aliases=["能源消耗强度", "能源消耗密度", "综合能源消耗强度", "综合能源消耗密度", "单位能源消耗", "单位产值综合能耗", "单位营收能源消耗", "能耗强度", "能耗密度"],
        required_any=["强度", "密度", "单位", "单耗"],
        forbidden_any=["总量", "总能耗", "综合能源消耗量"],
        unit_examples=["吨标准煤/万元", "吨标煤/万元", "千瓦时/万元", "兆瓦时/万元"],
    ),
    q_field(
        "natural_gas_consumption",
        "天然气消耗量",
        "E",
        "number",
        "energy",
        aliases=["天然气", "天然气消耗量", "天然气使用量", "天然气用量", "天然气耗用量"],
        required_any=["天然气"],
        forbidden_any=["排放因子", "排放系数", "换算系数", "核算方法"],
        unit_examples=["立方米", "万立方米", "m3", "m³", "吉焦"],
    ),
    q_field(
        "electricity_consumption",
        "用电量",
        "E",
        "number",
        "energy",
        aliases=["用电量", "耗电量", "电力消耗", "电力总量", "外购电力"],
        forbidden_any=["绿电", "可再生能源"],
        unit_examples=["千瓦时", "兆瓦时", "kWh", "MWh"],
    ),
    q_field(
        "water_consumption",
        "用水量",
        "E",
        "number",
        "water",
        aliases=["用水量", "取水量", "新鲜水用量", "总耗水量", "市政用水量", "市政购水量"],
        forbidden_any=["废水", "回用水", "循环水", "强度"],
        unit_examples=["吨", "立方米"],
    ),
    q_field(
        "wastewater_discharge",
        "废水排放量",
        "E",
        "number",
        "water",
        aliases=["废水排放量", "污水排放量", "废水排放总量"],
        forbidden_any=["回用水", "循环水"],
        unit_examples=["吨", "立方米"],
    ),
    q_field(
        "air_pollutant_emissions",
        "废气或大气污染物排放量",
        "E",
        "number",
        "mass",
        aliases=["废气排放量", "大气污染物排放量", "氮氧化物排放量", "二氧化硫排放量", "颗粒物排放量", "VOCs排放量"],
        unit_examples=["吨", "千克"],
    ),
    q_field(
        "non_hazardous_waste",
        "一般废弃物产生量",
        "E",
        "number",
        "waste",
        aliases=["一般废弃物产生量", "一般废弃物产生总量", "无害废弃物量", "无害废弃物产生量", "无害废弃物产生总量", "无害废弃物总量", "非危险废弃物", "非危险废弃物量", "非危险废弃物产生总量", "一般固体废弃物"],
        forbidden_any=["危险废弃物", "危废"],
        unit_examples=["吨", "千克"],
    ),
    q_field(
        "hazardous_waste",
        "危险废弃物产生量",
        "E",
        "number",
        "waste",
        aliases=["危险废弃物产生量", "危废产生量", "有害废弃物", "危险废物"],
        unit_examples=["吨", "千克"],
    ),
    q_field(
        "environmental_investment",
        "环保投入金额",
        "E",
        "number",
        "money",
        aliases=["环保投入", "环保总投资", "环保总投入", "环境保护投入", "环保投资"],
        unit_examples=["万元", "元", "百万元"],
    ),
    q_field(
        "environmental_penalty_count",
        "环境违规或处罚事件数量",
        "E",
        "number",
        "count",
        aliases=["环境违规或处罚事件数量", "环境处罚次数", "环保处罚", "环境违法违规事件", "环境行政处罚"],
        unit_examples=["次", "件", "起"],
    ),
]


__all__ = ["E_SCHEMA_DATA"]
