from typing import Any, Dict, List


def q_field(
    field_key: str,
    name_cn: str,
    category: str,
    value_type: str,
    unit_type: str,
    aliases: List[str],
    required_any: List[str] | None = None,
    forbidden_any: List[str] | None = None,
    unit_examples: List[str] | None = None,
    preferred_source: str = "appendix_table",
    unit_required: bool = True,
    year_required: bool = True,
) -> Dict[str, Any]:
    return {
        "field_key": field_key,
        "name_cn": name_cn,
        "category": category,
        "indicator_type": "quantitative",
        "value_type": value_type,
        "preferred_source": preferred_source,
        "unit_required": unit_required,
        "year_required": year_required,
        "unit_type": unit_type,
        "unit_examples": unit_examples or [],
        "aliases": aliases,
        "required_any": required_any if required_any is not None else aliases,
        "forbidden_any": forbidden_any or [],
    }


G_SCHEMA_DATA = [
    q_field(
        "board_size",
        "董事会人数",
        "G",
        "number",
        "person_count",
        aliases=["董事会人数", "董事人数", "董事会成员人数", "董事总数"],
        forbidden_any=["独立董事", "女性董事", "%", "比例", "高管", "高级管理人员"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "independent_directors",
        "独立董事人数",
        "G",
        "number",
        "person_count",
        aliases=["独立董事人数", "独立董事数量", "独董人数"],
        forbidden_any=["比例", "%"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "independent_director_ratio",
        "独立董事比例",
        "G",
        "percentage",
        "percentage",
        aliases=["独立董事比例", "独立董事占比", "独董比例", "独董占比"],
        forbidden_any=["人数", "数量", "审计委员会", "提名委员会", "薪酬与考核委员会", "专门委员会"],
        unit_examples=["%"],
    ),
    q_field(
        "female_directors",
        "女性董事人数",
        "G",
        "number",
        "person_count",
        aliases=["女性董事人数", "女董事人数", "女性董事数量", "女性董事"],
        forbidden_any=["比例", "%"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "board_meetings",
        "董事会会议次数",
        "G",
        "number",
        "count",
        aliases=["董事会会议次数", "董事会召开次数", "召开董事会", "董事会会议"],
        forbidden_any=["股东大会", "监事会", "专门委员会", "战略委员会", "审计委员会", "提名委员会", "薪酬与考核委员会"],
        unit_examples=["次", "场"],
    ),
    q_field(
        "shareholder_meetings",
        "股东大会会议次数",
        "G",
        "number",
        "count",
        aliases=["股东大会会议次数", "股东大会召开次数", "股东大会次数", "召开股东大会"],
        forbidden_any=["董事会", "监事会"],
        unit_examples=["次", "场"],
    ),
    q_field(
        "anti_corruption_training_sessions",
        "反腐败培训次数",
        "G",
        "number",
        "count",
        aliases=["反腐败培训次数", "廉洁培训次数", "反舞弊培训次数", "商业道德培训次数"],
        forbidden_any=["人数", "人次", "小时"],
        unit_examples=["次", "场"],
    ),
    q_field(
        "anti_corruption_training_participants",
        "反腐败培训人数",
        "G",
        "number",
        "person_time",
        aliases=["反腐败培训人数", "廉洁培训人数", "反舞弊培训人数", "商业道德培训人数", "反腐败培训人次"],
        forbidden_any=["次数", "小时"],
        unit_examples=["人", "人次"],
    ),
    q_field(
        "confirmed_corruption_cases",
        "确认腐败案件数量",
        "G",
        "number",
        "count",
        aliases=["确认腐败案件数量", "腐败案件数量", "贪污腐败案件", "商业贿赂案件"],
        forbidden_any=["培训"],
        unit_examples=["件", "起", "宗"],
    ),
]


__all__ = ["G_SCHEMA_DATA"]
