from typing import Any, Dict, List


def q_field(
    field_key: str,
    name_cn: str,
    category: str,
    value_type: str,
    unit_type: str,
    aliases: List[str],
    required_any: List[str] | None = None,
    forbidden_any: List[str] | None = None,
    unit_examples: List[str] | None = None,
    preferred_source: str = "appendix_table",
    unit_required: bool = True,
    year_required: bool = True,
) -> Dict[str, Any]:
    return {
        "field_key": field_key,
        "name_cn": name_cn,
        "category": category,
        "indicator_type": "quantitative",
        "value_type": value_type,
        "preferred_source": preferred_source,
        "unit_required": unit_required,
        "year_required": year_required,
        "unit_type": unit_type,
        "unit_examples": unit_examples or [],
        "aliases": aliases,
        "required_any": required_any if required_any is not None else aliases,
        "forbidden_any": forbidden_any or [],
    }


S_SCHEMA_DATA = [
    q_field(
        "total_employees",
        "员工总数",
        "S",
        "number",
        "person_count",
        aliases=["员工总数", "雇员总数", "员工人数", "在职员工总数", "员工总人数"],
        forbidden_any=[
            "男性",
            "女性",
            "少数民族",
            "30岁",
            "50岁",
            "按年龄",
            "按性别",
            "按职位",
            "按员工类别",
            "培训",
            "董事",
            "体检",
            "探亲",
        ],
        unit_examples=["人", "名"],
    ),
    q_field(
        "male_employees",
        "男性员工人数",
        "S",
        "number",
        "person_count",
        aliases=["男性员工人数", "男员工人数", "男性雇员人数", "男性员工"],
        forbidden_any=["比例", "%", "女性", "高级管理层", "执行管理层", "管理层"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "female_employees",
        "女性员工人数",
        "S",
        "number",
        "person_count",
        aliases=["女性员工人数", "女员工人数", "女性雇员人数", "女性员工"],
        forbidden_any=[
            "比例",
            "%",
            "男性",
            "女性管理层",
            "高级管理层",
            "执行管理层",
            "管理层",
            "育儿假",
            "产假",
            "生育假",
            "享受假期",
        ],
        unit_examples=["人", "名"],
    ),
    q_field(
        "female_employee_ratio",
        "女性员工比例",
        "S",
        "percentage",
        "percentage",
        aliases=["女性员工比例", "女性员工占比", "女员工占比", "女性雇员比例"],
        forbidden_any=["女性管理层", "女性董事"],
        unit_examples=["%"],
    ),
    q_field(
        "employee_turnover_rate",
        "员工流失率",
        "S",
        "percentage",
        "percentage",
        aliases=["员工流失率", "员工离职率", "雇员流失率", "员工流动率"],
        unit_examples=["%"],
    ),
    q_field(
        "training_total_hours",
        "员工培训总时长",
        "S",
        "number",
        "hour",
        aliases=[
            "员工培训总时长",
            "培训总时长",
            "培训总小时",
            "员工培训总小时数",
            "累计培训时长",
            "安全培训总时长",
        ],
        forbidden_any=["人均", "供应商", "反腐败", "廉洁", "商业道德"],
        unit_examples=["小时"],
    ),
    q_field(
        "training_hours_per_employee",
        "人均培训时长",
        "S",
        "number",
        "hour",
        aliases=["人均培训时长", "员工平均培训时数", "员工受训平均时数", "平均培训时数", "平均培训小时数"],
        required_any=["人均", "平均"],
        forbidden_any=["高层", "中层", "基层", "新员工", "新入职", "反腐败", "廉洁", "安全培训"],
        unit_examples=["小时", "小时/人"],
    ),
    q_field(
        "training_coverage_rate",
        "员工培训覆盖率",
        "S",
        "percentage",
        "percentage",
        aliases=["员工培训覆盖率", "培训覆盖率", "受训员工比例", "员工培训参与率"],
        forbidden_any=["税务", "供应商", "安全", "质量", "环保", "反腐败", "反贪污", "商业贿赂", "廉洁", "合规"],
        unit_examples=["%"],
    ),
    q_field(
        "social_security_coverage",
        "社会保险覆盖率",
        "S",
        "percentage",
        "percentage",
        aliases=["社会保险覆盖率", "社保覆盖率", "员工社保覆盖率", "社会保险参保率", "社会保险缴纳覆盖率"],
        required_any=["社会保险", "社保"],
        unit_examples=["%"],
    ),
    q_field(
        "employee_medical_checkup_coverage",
        "员工体检覆盖率",
        "S",
        "percentage",
        "percentage",
        aliases=["员工体检覆盖率", "体检覆盖率", "员工健康体检覆盖率", "职业健康体检覆盖率"],
        required_any=["体检", "健康体检"],
        unit_examples=["%"],
    ),
    q_field(
        "trained_employees_count",
        "受训员工人数",
        "S",
        "number",
        "person_time",
        aliases=[
            "受训员工人数",
            "培训员工人数",
            "参与培训员工人数",
            "员工培训人次",
            "受训人次",
            "接受培训总人数",
            "接受培训总人次",
            "员工接受培训总人数",
        ],
        unit_examples=["人", "人次"],
    ),
    q_field(
        "safety_accident_count",
        "安全生产事故数量",
        "S",
        "number",
        "count",
        aliases=["安全生产事故数量", "安全事故数", "生产安全事故数", "生产安全事故", "工伤事故数量"],
        unit_examples=["起", "次", "件"],
    ),
    q_field(
        "occupational_health_safety_investment",
        "安全生产投入",
        "S",
        "number",
        "money",
        aliases=["安全生产投入", "职业健康安全投入", "安全投入", "安全生产费用", "安全费用投入"],
        required_any=["安全", "职业健康"],
        forbidden_any=["事故", "次数", "演练"],
        unit_examples=["万元", "元", "百万元"],
    ),
    q_field(
        "safety_emergency_drill_count",
        "安全应急演练次数",
        "S",
        "number",
        "count",
        aliases=["安全应急演练次数", "应急演练次数", "安全演练次数", "应急演练场次", "安全应急演练场次"],
        required_any=["演练"],
        forbidden_any=["培训", "投入", "事故"],
        unit_examples=["次", "场"],
    ),
    q_field(
        "lost_work_days_due_to_injury",
        "因工伤损失工作日数",
        "S",
        "number",
        "count",
        aliases=["因工伤损失工作日数", "工伤损失工作日", "损失工时", "因工伤损失天数"],
        unit_examples=["天", "日", "小时"],
    ),
    q_field(
        "r_and_d_personnel_count",
        "研发人员数量",
        "S",
        "number",
        "person_count",
        aliases=["研发人员数量", "研发人员人数", "研发员工人数", "研发人员总数"],
        forbidden_any=["比例", "%", "投入"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "r_and_d_expense",
        "研发投入金额",
        "S",
        "number",
        "money",
        aliases=["研发投入金额", "研发投入", "公司研发总投入", "研发费用", "研发支出"],
        forbidden_any=["研发人员"],
        unit_examples=["万元", "元", "百万元"],
    ),
    q_field(
        "public_welfare_investment",
        "公益投入金额",
        "S",
        "number",
        "money",
        aliases=["公益投入金额", "公益投入", "社会公益投入", "慈善捐赠金额", "对外捐赠", "对外捐赠金额"],
        unit_examples=["万元", "元", "百万元"],
    ),
]


__all__ = ["S_SCHEMA_DATA"]
