# config/core_schema.py
"""
Core ESG Schema v4.1

设计目标：
1. 构建跨行业通用 ESG 核心指标体系；
2. 用于 all_table_rows -> standard_esg_results 的标准化匹配；
3. 无法映射到本 Schema 的指标进入 unknown_metrics；
4. 本版根据批量评估和误差分析做了小步更新：
   - 补充已有 Core 字段别名；
   - 新增 anti_corruption_training_hours；
   - 新增 patent_applications_new；
   - 没有把经营绩效、行业特色、单一公司特色指标纳入 Core。
"""

from typing import Dict, List, Any


def q_field(
    field_key: str,
    name_cn: str,
    category: str,
    value_type: str,
    unit_type: str,
    aliases: List[str],
    required_any: List[str] | None = None,
    forbidden_any: List[str] | None = None,
    unit_examples: List[str] | None = None,
    preferred_source: str = "appendix_table",
    unit_required: bool = True,
    year_required: bool = True,
) -> Dict[str, Any]:
    return {
        "field_key": field_key,
        "name_cn": name_cn,
        "category": category,
        "indicator_type": "quantitative",
        "value_type": value_type,
        "preferred_source": preferred_source,
        "unit_required": unit_required,
        "year_required": year_required,
        "unit_type": unit_type,
        "unit_examples": unit_examples or [],
        "aliases": aliases,
        "required_any": required_any if required_any is not None else aliases,
        "forbidden_any": forbidden_any or [],
    }


def t_field(
    field_key: str,
    name_cn: str,
    category: str,
    aliases: List[str],
    required_any: List[str] | None = None,
    forbidden_any: List[str] | None = None,
    preferred_source: str = "main_text_rag",
) -> Dict[str, Any]:
    return {
        "field_key": field_key,
        "name_cn": name_cn,
        "category": category,
        "indicator_type": "qualitative",
        "value_type": "boolean_or_text",
        "preferred_source": preferred_source,
        "unit_required": False,
        "year_required": False,
        "unit_type": "text",
        "unit_examples": [],
        "aliases": aliases,
        "required_any": required_any if required_any is not None else aliases,
        "forbidden_any": forbidden_any or ["指标索引", "内容索引", "报告页码", "对应章节", "GRI"],
    }


CORE_SCHEMA = [
    # =====================================================
    # E - Environmental 环境类：25 个
    # =====================================================
    q_field(
        "total_ghg_emissions",
        "温室气体排放总量",
        "E",
        "number",
        "ghg",
        aliases=["温室气体排放总量", "温室气体总排放量", "碳排放总量", "温室气体排放量"],
        required_any=["温室气体排放总量", "温室气体总排放量", "碳排放总量", "温室气体排放量"],
        forbidden_any=["范围一","范围1","范围 1","scope1","scope 1","直接温室气体","范围二","范围2","范围 2","scope2","scope 2","间接温室气体","范围三","范围3","范围 3","scope3","scope 3","排放强度","密度",],
        unit_examples=["吨CO2e", "吨二氧化碳当量", "万吨CO2e"],
    ),
    q_field(
        "scope_1_emissions",
        "范围一温室气体排放量",
        "E",
        "number",
        "ghg",
        aliases=["范围一排放", "范围一温室气体排放", "直接温室气体排放", "直接温室气体排放量", "直接温室气体排放总量"],
        required_any=["范围一","范围1", "范围 1","scope1","scope 1","直接温室气体",],
        forbidden_any=["范围二", "Scope2", "间接温室气体", "排放强度"],
        unit_examples=["吨CO2e", "吨二氧化碳当量"],
    ),
    q_field(
        "scope_2_emissions",
        "范围二温室气体排放量",
        "E",
        "number",
        "ghg",
        aliases=["范围二排放", "范围二温室气体排放", "间接温室气体排放", "间接温室气体排放量", "间接温室气体排放总量"],
        required_any=["范围二","范围2","范围 2","scope2","scope 2","间接温室气体",],
        forbidden_any=["范围一", "Scope1", "直接温室气体", "排放强度"],
        unit_examples=["吨CO2e", "吨二氧化碳当量"],
    ),
    q_field(
        "scope_3_emissions",
        "范围三温室气体排放量",
        "E",
        "number",
        "ghg",
        aliases=[
            "范围三排放",
            "范围三温室气体排放",
            "范围三温室气体排放量",
            "范围 3 温室气体排放量",
            "范围3温室气体排放量",
            "Scope 3 排放",
            "Scope3 排放",
        ],
        required_any=[
            "范围三",
            "范围3",
            "范围 3",
            "scope3",
            "scope 3",
        ],
        forbidden_any=[
            "范围一",
            "范围1",
            "范围二",
            "范围2",
            "排放强度",
            "密度",
            "上游",
            "下游",
            "上游排放",
            "下游排放",
            "外购商品和服务",
            "员工通勤",
            "商务旅行",
            "差旅",
            "资本货物",
            "燃料和能源相关活动",
        ],
        unit_examples=["吨CO2e", "吨二氧化碳当量", "万吨二氧化碳当量"],
    ),
    q_field(
        "ghg_emissions_intensity",
        "温室气体排放强度",
        "E",
        "number",
        "intensity",
        aliases=["温室气体排放强度", "碳排放强度", "单位收入碳排放", "单位产值碳排放","温室气体排放密度","碳排放密度","单位营收温室气体排放",],
        required_any=["排放强度", "碳排放强度", "单位收入碳排放", "单位产值碳排放","温室气体排放密度","碳排放密度","单位营收温室气体排放",],
        forbidden_any=["排放总量"],
        unit_examples=["吨CO2e/万元", "吨CO2e/吨产品"],
    ),
    q_field(
        "energy_consumption_total",
        "能源消耗总量",
        "E",
        "number",
        "energy",
        aliases=["能源消耗总量", "综合能耗", "总能源消耗", "综合能源消耗量", "能源消耗量"],
        required_any=["能源消耗总量", "综合能耗", "总能源消耗", "综合能源消耗量", "能源消耗量"],
        forbidden_any=["强度", "单位", "电使用量", "用电量", "耗电量", "外购电力"],
        unit_examples=["吨标准煤", "吨标煤", "MWh", "万千瓦时"],
    ),
    q_field(
        "energy_consumption_intensity",
        "能源消耗强度",
        "E",
        "number",
        "intensity",
        aliases=["能源消耗强度", "综合能耗强度", "能耗强度", "单位收入能耗", "单位产值能耗","能源消耗密度","能源使用密度","单位营收能源消耗",],
        required_any=["强度", "单位收入能耗", "单位产值能耗", "能耗强度","能源消耗密度","能源使用密度","单位营收能源消耗",],
        forbidden_any=["能源消耗总量", "综合能耗总量"],
        unit_examples=["吨标准煤/万元", "吨标煤/万元"],
    ),
    q_field(
        "electricity_consumption",
        "电力消耗量",
        "E",
        "number",
        "energy",
        aliases=["电力消耗", "用电量", "耗电量", "外购电力", "电使用量", "营业办公消耗电力", "电力使用量","电力"],
        required_any=["电力消耗", "用电量", "耗电量", "外购电力", "电使用量", "营业办公消耗电力", "电力使用量","电力"],
        forbidden_any=["光伏", "新能源发电量", "清洁能源", "可再生能源", "绿色电力"],
        unit_examples=["千瓦时", "万千瓦时", "MWh","兆瓦时"],
    ),
    q_field(
        "renewable_energy_consumption",
        "可再生能源使用量",
        "E",
        "number",
        "energy",
        aliases=["可再生能源使用量", "可再生能源消耗量", "绿色电力", "清洁能源使用量", "光伏等新能源发电量", "新能源发电量"],
        required_any=["可再生能源", "绿色电力", "清洁能源", "光伏", "新能源发电"],
        forbidden_any=["化石能源", "煤炭", "天然气"],
        unit_examples=["千瓦时", "万千瓦时", "吨标准煤"],
    ),
    q_field(
        "natural_gas_consumption",
        "天然气消耗量",
        "E",
        "number",
        "gas",
        aliases=["天然气消耗量", "天然气使用量", "天然气用量"],
        required_any=["天然气"],
        forbidden_any=[],
        unit_examples=["立方米", "万立方米"],
    ),
    q_field(
        "coal_consumption",
        "煤炭消耗量",
        "E",
        "number",
        "mass",
        aliases=["煤炭消耗量", "煤耗", "原煤消耗量", "煤使用量"],
        required_any=["煤炭", "煤耗", "原煤"],
        forbidden_any=["替代化石能源"],
        unit_examples=["吨", "万吨"],
    ),
    q_field(
        "water_consumption",
        "水资源消耗量",
        "E",
        "number",
        "water",
        aliases=["总耗水量", "用水量", "取水量", "耗水量", "新鲜水用量", "营业办公耗水", "水资源消耗量"],
        required_any=["总耗水量", "用水量", "取水量", "耗水量", "新鲜水用量", "营业办公耗水", "水资源消耗量"],
        forbidden_any=["废水", "循环", "回用", "节水", "强度", "密度"],
        unit_examples=["吨", "万吨", "立方米", "万立方米"],
    ),
    q_field(
        "water_consumption_intensity",
        "水资源消耗强度",
        "E",
        "number",
        "intensity",
        aliases=[
            "水资源消耗强度",
            "用水强度",
            "耗水强度",
            "单位收入耗水",
            "单位产值耗水",
            "水资源使用强度",
            "水资源使用密度",
            "单位营收水资源使用量",
        ],
        required_any=[
            "用水强度",
            "耗水强度",
            "水资源消耗强度",
            "单位收入耗水",
            "单位产值耗水",
            "水资源使用强度",
            "水资源使用密度",
            "单位营收水资源使用量",
        ],
        forbidden_any=["总耗水量", "总用水量"],
        unit_examples=["吨/万元", "立方米/万元"],
    ),
    q_field(
        "recycled_water_volume",
        "循环水或回用水量",
        "E",
        "number",
        "water",
        aliases=["循环水使用量", "循环用水量", "循环水量", "回用水量", "中水回用量", "再生水使用量"],
        required_any=["循环水", "循环用水", "回用水", "中水回用", "再生水"],
        forbidden_any=["总耗水量", "废水排放量"],
        unit_examples=["吨", "万吨", "立方米", "万立方米"],
    ),
    q_field(
        "wastewater_discharge",
        "废水排放量",
        "E",
        "number",
        "water",
        aliases=["废水排放量", "污水排放量"],
        required_any=["废水排放", "污水排放"],
        forbidden_any=["废水处理", "废水达标率", "循环水", "回用水"],
        unit_examples=["吨", "万吨", "立方米", "万立方米"],
    ),
    q_field(
        "cod_emissions",
        "化学需氧量排放量",
        "E",
        "number",
        "mass",
        aliases=["化学需氧量排放量", "COD排放量", "COD", "化学需氧量"],
        required_any=["化学需氧量", "COD"],
        forbidden_any=[],
        unit_examples=["吨", "千克"],
    ),
    q_field(
        "ammonia_nitrogen_emissions",
        "氨氮排放量",
        "E",
        "number",
        "mass",
        aliases=["氨氮排放量", "氨氮"],
        required_any=["氨氮"],
        forbidden_any=[],
        unit_examples=["吨", "千克"],
    ),
    q_field(
        "so2_emissions",
        "二氧化硫排放量",
        "E",
        "number",
        "mass",
        aliases=["二氧化硫排放量", "SO2排放量", "硫氧化物排放量", "硫氧化物", "氧化硫", "SOX", "SOx"],
        required_any=["二氧化硫", "SO2", "硫氧化物", "氧化硫", "SOx", "SOX"],
        forbidden_any=[
            "氮氧化物",
            "NOx",
            "NOX",
            "削减",
            "削减量",
            "减排",
            "减排量",
            "减少量",
        ],
        unit_examples=["吨", "千克"],
    ),
    q_field(
        "nox_emissions",
        "氮氧化物排放量",
        "E",
        "number",
        "mass",
        aliases=["氮氧化物排放量", "NOx排放量", "NOX排放量", "氮氧化物"],
        required_any=["氮氧化物", "NOx", "NOX"],
        forbidden_any=[
            "二氧化硫",
            "SO2",
            "硫氧化物",
            "削减",
            "削减量",
            "减排",
            "减排量",
            "减少量",
        ],
        unit_examples=["吨", "千克"],
    ),
    q_field(
        "particulate_matter_emissions",
        "颗粒物排放量",
        "E",
        "number",
        "mass",
        aliases=["颗粒物排放量", "烟尘排放量", "颗粒物", "烟尘"],
        required_any=["颗粒物", "烟尘"],
        forbidden_any=["削减", "削减量", "减排", "减排量", "减少量"],
        unit_examples=["吨", "千克"],
    ),
    q_field(
        "hazardous_waste",
        "危险废弃物产生或排放量",
        "E",
        "number",
        "waste",
        aliases=["危险废物", "危险废弃物", "有害废弃物", "危废", "危险废弃物排放量", "危险废弃物产生量"],
        required_any=["危险废物", "危险废弃物", "有害废弃物", "危废"],
        forbidden_any=[
            "一般固体废弃物",
            "无害废弃物",
            "非危险废物",
            "密度",
            "强度",
            "单位营收",
            "单位收入",
            "每万元",
            "每亿元",
            "循环利用",
            "回收利用",
            "再利用",
            "利用量",
            "回收量",
        ],
        unit_examples=["吨", "万吨"],
    ),
    q_field(
        "non_hazardous_waste",
        "无害废弃物产生或排放量",
        "E",
        "number",
        "waste",
        aliases=["一般固体废弃物", "无害废弃物", "非危险废物", "一般废弃物", "无害废弃物产生量"],
        required_any=["一般固体废弃物", "无害废弃物", "非危险废物", "一般废弃物"],
        forbidden_any=[
            "危险废物",
            "危险废弃物",
            "有害废弃物",
            "危废",
            "密度",
            "强度",
            "单位营收",
            "单位收入",
            "每万元",
            "每亿元",
            "循环利用",
            "回收利用",
            "再利用",
            "利用量",
            "回收量",
        ],
        unit_examples=["吨", "万吨"],
    ),
    q_field(
        "total_waste",
        "废弃物总量",
        "E",
        "number",
        "waste",
        aliases=["废弃物产生总量", "固体废弃物总量", "废弃物总量", "废弃物排放总量"],
        required_any=["废弃物总量", "废弃物产生总量", "固体废弃物总量", "废弃物排放总量"],
        forbidden_any=[
            "危险废物",
            "危险废弃物",
            "一般固体废弃物",
            "无害废弃物",
            "回收利用",
            "循环利用",
            "再利用",
            "利用量",
            "回收量",
        ],
        unit_examples=["吨", "万吨"],
    ),
    q_field(
        "waste_recycling_rate",
        "废弃物回收利用率",
        "E",
        "percentage",
        "percentage",
        aliases=["废弃物回收利用率", "回收利用率", "回收率", "废弃物回收率"],
        required_any=["回收利用率", "回收率"],
        forbidden_any=[],
        unit_examples=["%"],
    ),
    q_field(
        "environmental_investment",
        "环保投入金额",
        "E",
        "number",
        "money",
        aliases=["环保投入", "环境保护投入", "环保投资", "环保总投资", "环境治理投入金额","环保总投入"],
        required_any=["环保投入", "环境保护投入", "环保投资", "环保总投资", "环境治理投入","环保总投入"],
        forbidden_any=["培训投入", "研发投入"],
        unit_examples=["万元", "亿元"],
    ),
    q_field(
        "environmental_violation_cases",
        "环境违规或处罚事件数量",
        "E",
        "number",
        "count",
        aliases=["环境违规事件数量", "环境处罚次数", "环保处罚", "环境违法事件", "因环境事件受到生态环境等有关部门重大行政处罚的处罚事件", "环境行政处罚事件"],
        required_any=["环境违规", "环境处罚", "环保处罚", "环境违法", "重大行政处罚", "生态环境"],
        forbidden_any=["培训", "演练"],
        unit_examples=["次", "件", "宗"],
    ),

    # =====================================================
    # S - Social 社会类：25 个
    # =====================================================
    q_field(
        "total_employees",
        "员工总数",
        "S",
        "number",
        "person_count",
        aliases=["员工总数", "员工总人数", "雇员总数", "人员总数", "员工人数", "总员工数"],
        required_any=["员工总数", "员工总人数", "雇员总数", "人员总数", "员工人数", "总员工数"],
        forbidden_any=[
            "男性",
            "女性",
            "少数民族",
            "30岁",
            "40岁",
            "50岁",
            "培训",
            "反腐败",
            "反贪污",
            "反商业贿赂",
            "参加",
            "参与",
            "受训",
            "按性别",
            "按年龄",
        ],
        unit_examples=["人", "名"],
    ),
    q_field(
        "male_employees",
        "男性员工人数",
        "S",
        "number",
        "person_count",
        aliases=["男性员工人数", "男性员工数量", "男员工人数", "男性员工", "男性"],
        required_any=["男性员工", "男员工", "男性"],
        forbidden_any=["比例", "占比", "%", "女性", "管理层"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "female_employees",
        "女性员工人数",
        "S",
        "number",
        "person_count",
        aliases=["女性员工人数", "女性员工数量", "女员工人数", "女性员工", "女性"],
        required_any=["女性员工", "女员工", "女性"],
        forbidden_any=["比例", "占比", "%", "男性", "管理层", "女性管理"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "female_employee_ratio",
        "女性员工比例",
        "S",
        "percentage",
        "percentage",
        aliases=["女性员工比例", "女性员工占比", "女性雇员比例"],
        required_any=["女性员工比例", "女性员工占比", "女性雇员比例"],
        forbidden_any=["女性管理层", "女性管理人员", "中层管理层"],
        unit_examples=["%"],
    ),
    q_field(
        "female_management_ratio",
        "女性管理层比例",
        "S",
        "percentage",
        "percentage",
        aliases=["女性管理层比例", "女性管理人员占比", "管理人员中女性人数比例", "中层管理层中的女性员工比例", "女性管理者比例"],
        required_any=["女性管理层", "女性管理人员", "管理人员中女性", "中层管理层中的女性", "女性管理者"],
        forbidden_any=["女性员工人数", "女性员工数量"],
        unit_examples=["%"],
    ),
    q_field(
        "minority_employees",
        "少数民族员工人数",
        "S",
        "number",
        "person_count",
        aliases=["少数民族员工人数", "少数民族员工数量", "少数民族人数", "少数民族"],
        required_any=["少数民族"],
        forbidden_any=["非少数民族"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "employees_under_30",
        "30岁以下员工人数",
        "S",
        "number",
        "person_count",
        aliases=["30岁以下员工人数", "30岁以下", "30周岁以下", "30岁及30岁以下", "30岁以下（不含30岁）", "<30岁", "小于30岁"],
        required_any=["30岁以下", "30周岁以下", "30岁及30岁以下", "<30岁", "小于30岁"],
        forbidden_any=["30-40", "30至40", "40-50", "40至50", "50岁"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "employees_30_to_50",
        "30至50岁员工人数",
        "S",
        "number",
        "person_count",
        aliases=["30至50岁员工人数", "30-50岁员工人数", "30岁至50岁员工人数", "30岁-50岁", "30岁至50岁", "大于30岁且小于50岁"],
        required_any=["30至50", "30-50", "30岁至50", "30岁-50岁", "30岁至50岁", "大于30岁且小于50岁"],
        forbidden_any=["30岁以下", "50岁以上", "50岁及以上", "30-40", "30至40", "40-50", "40至50"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "employees_over_50",
        "50岁以上员工人数",
        "S",
        "number",
        "person_count",
        aliases=["50岁以上员工人数", "50岁及以上", "50周岁以上", "50岁及50岁以上", ">50岁", "大于50岁"],
        required_any=["50岁以上", "50岁及以上", "50周岁以上", "50岁及50岁以上", ">50岁", "大于50岁"],
        forbidden_any=["30岁以下", "30-40", "30至40", "40-50", "40至50"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "employee_turnover_rate",
        "员工流失率",
        "S",
        "percentage",
        "percentage",
        aliases=["员工流失率", "离职率", "员工离职率"],
        required_any=["员工流失率", "离职率", "员工离职率"],
        forbidden_any=["人数", "数量"],
        unit_examples=["%"],
    ),
    q_field(
        "training_total_hours",
        "员工培训总时长",
        "S",
        "number",
        "hour",
        aliases=[
            "员工培训总时长",
            "培训总小时数",
            "培训总时数",
            "员工受训总时数",
            "员工培训总学时",
            "培训总学时",
            "全体员工培训总学时",
            "全体员工总受训时长",
        ],
        required_any=[
            "培训总时长",
            "培训总小时",
            "培训总时数",
            "员工受训总时数",
            "员工培训总学时",
            "培训总学时",
            "全体员工培训总学时",
            "全体员工总受训时长",
        ],
        forbidden_any=["人均", "平均", "志愿服务", "公益慈善", "反腐败", "反贪污", "反商业贿赂", "安全生产", "安全培训", "环保培训", "质量培训"],
        unit_examples=["小时", "学时"],
    ),
    q_field(
        "training_hours_per_employee",
        "人均培训时长",
        "S",
        "number",
        "hour",
        aliases=["人均培训时长", "人均培训小时数", "员工平均培训时数", "员工受训平均时数", "平均培训时数", "每名员工培训时数"],
        required_any=["人均培训", "平均培训时数", "员工平均培训时数", "员工受训平均时数", "每名员工培训时数"],
        forbidden_any=["高层", "中层", "基层", "新员工", "新入职", "男性", "女性", "反腐败", "反贪污", "反商业贿赂", "安全生产", "安全培训", "培训总时长"],
        unit_examples=["小时", "小时/人"],
    ),
    q_field(
        "training_coverage_rate",
        "员工培训覆盖率",
        "S",
        "percentage",
        "percentage",
        aliases=["员工培训覆盖率", "培训覆盖率", "员工受训覆盖率", "受训员工比例", "参加培训的员工覆盖率"],
        required_any=["员工培训覆盖率", "培训覆盖率", "员工受训覆盖率", "受训员工比例", "参加培训的员工覆盖率"],
        forbidden_any=["反腐败", "反贪污", "反商业贿赂", "安全生产", "健康档案", "工伤保险","采购","供应商","专项培训","环保培训","安全培训","质量培训",],
        unit_examples=["%"],
    ),
    q_field(
        "training_expense",
        "培训投入金额",
        "S",
        "number",
        "money",
        aliases=["培训投入", "培训费用", "培训支出费用", "培训费用总支出", "员工培训投入金额"],
        required_any=["培训投入", "培训费用", "培训支出"],
        forbidden_any=["培训总时长", "人均培训", "志愿服务"],
        unit_examples=["万元", "元"],
    ),
    q_field(
        "trained_employees_count",
        "受训员工人数或人次",
        "S",
        "number",
        "person_time",
        aliases=[
            "参加培训的员工总数",
            "受训员工人数",
            "参加培训员工人数",
            "培训总人次",
            "受训员工人次",
            "员工受训总人次",
            "全体员工受训总人次",
            "累计参加培训学员人数",
        ],
        required_any=[
            "参加培训",
            "受训员工",
            "培训总人次",
            "员工受训总人次",
            "全体员工受训总人次",
            "累计参加培训学员人数",
        ],
        forbidden_any=[
            "培训覆盖率",
            "人均培训",
            "培训费用",
            "培训总时长",
            "小时",
            "学时",
            "反腐败",
            "反贪污",
            "反商业贿赂",
            "安全生产",
            "安全培训",
            "环保",
            "环境保护",
            "环境合规",
        ],
        unit_examples=["人", "人次"],
    ),
    q_field(
        "work_injury_rate",
        "工伤率",
        "S",
        "number_or_percentage",
        "percentage_or_rate",
        aliases=["工伤率", "工伤事故率"],
        required_any=["工伤率", "工伤事故率"],
        forbidden_any=["因工死亡", "工亡", "损失工作日", "损失工时", "总工伤人数", "安全事故数"],
        unit_examples=["%", "次/百万工时"],
    ),
    q_field(
        "work_related_fatalities",
        "因工死亡人数",
        "S",
        "number",
        "person_count",
        aliases=["因工死亡人数", "工亡人数", "工作相关死亡人数", "因工作关系死亡总人数", "因工作关系死亡人数"],
        required_any=["因工死亡", "工亡", "工作相关死亡", "因工作关系死亡"],
        forbidden_any=["工伤率", "损失工作日", "损失工时"],
        unit_examples=["人", "次"],
    ),
    q_field(
        "lost_workdays_due_to_injury",
        "因工伤损失工作日数",
        "S",
        "number",
        "day_or_hour",
        aliases=["因工伤损失工作日数", "因工伤损失工时", "损失工作日", "损失工时", "员工因工伤损失总天数", "工伤损失总天数"],
        required_any=["损失工作日", "损失工时", "员工因工伤损失总天数", "工伤损失总天数"],
        forbidden_any=["因工死亡", "工亡"],
        unit_examples=["天", "小时"],
    ),
    q_field(
        "social_insurance_coverage_rate",
        "社会保险覆盖率",
        "S",
        "percentage",
        "percentage",
        aliases=["社会保险覆盖率", "社保覆盖率", "工伤保险人员覆盖率", "工伤保险覆盖率"],
        required_any=["社会保险覆盖率", "社保覆盖率", "工伤保险人员覆盖率", "工伤保险覆盖率"],
        forbidden_any=["培训覆盖率", "健康档案"],
        unit_examples=["%"],
    ),
    q_field(
        "employee_health_record_coverage_rate",
        "员工健康档案或体检覆盖率",
        "S",
        "percentage",
        "percentage",
        aliases=["员工健康档案覆盖率", "职业健康档案覆盖率", "健康档案覆盖率", "员工体检覆盖率", "体检覆盖率"],
        required_any=["健康档案覆盖率", "职业健康档案覆盖率", "员工体检覆盖率", "体检覆盖率"],
        forbidden_any=["培训覆盖率", "社保覆盖率", "社会保险"],
        unit_examples=["%"],
    ),
    q_field(
        "r_and_d_investment",
        "研发投入金额",
        "S",
        "number",
        "money",
        aliases=["研发投入", "科技研发投入", "研发费用", "研发资金投入"],
        required_any=["研发投入", "科技研发投入", "研发费用", "研发资金"],
        forbidden_any=["研发人员", "研发团队", "研发队伍", "比例", "占比"],
        unit_examples=["万元", "亿元"],
    ),
    q_field(
        "r_and_d_employees",
        "研发人员数量",
        "S",
        "number",
        "person_count",
        aliases=["研发人员数量", "研发队伍人数", "研发员工人数", "研发团队总人数", "研发团队人数", "研发人员总数"],
        required_any=["研发人员", "研发团队", "研发队伍", "研发员工"],
        forbidden_any=["研发投入", "研发费用", "研发资金", "比例", "占比", "%"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "authorized_patents_new",
        "当年新增授权专利数量",
        "S",
        "number",
        "count",
        aliases=["新增授权专利数量", "新增授权专利数", "当年授权专利数量", "报告当年授权的专利总数", "获得科技发明专利授权证书"],
        required_any=["新增授权专利", "当年授权专利", "报告当年授权", "获得科技发明专利授权证书"],
        forbidden_any=["累计", "有效期内", "有效专利拥有量"],
        unit_examples=["项", "件", "个"],
    ),
    q_field(
        "authorized_patents_total",
        "累计授权专利数量",
        "S",
        "number",
        "count",
        aliases=["累计拥有授权专利数量", "累计授权专利数量", "有效专利拥有量", "授权且有效专利拥有量", "授权专利累计数", "授权专利累计数（有效期内的专利数）","截至报告期末有效专利数量","有效专利数量","报告期末有效专利数量", "有效期内的专利数","报告期内有效专利数"],
        required_any=["累计授权专利", "授权专利累计", "有效期内的专利", "有效专利拥有量", "授权且有效专利","报告期内有效专利数","截至报告期末有效专利数量","有效专利数量","报告期末有效专利数量",],
        forbidden_any=["新增", "当年", "申请"],
        unit_examples=["项", "件", "个"],
    ),
    q_field(
        "customer_complaints",
        "客户投诉数量",
        "S",
        "number",
        "count",
        aliases=["客户投诉数量", "客户投诉案件数量", "客户投诉次数", "投诉数量"],
        required_any=["客户投诉", "投诉数量", "投诉次数"],
        forbidden_any=["投诉解决率", "举报", "申诉", "举报机制"],
        unit_examples=["件", "起", "次"],
    ),

    # =====================================================
    # G - Governance 治理量化类：12 个
    # =====================================================
    q_field(
        "board_size",
        "董事会人数",
        "G",
        "number",
        "person_count",
        aliases=["董事会人数", "董事人数"],
        required_any=["董事会人数", "董事人数","董事会成员","董事会成员的人数",],
        forbidden_any=["培训", "反腐败", "反贪污", "反商业贿赂", "占比", "比例", "百分比", "%","不兼任","不兼任高管","高管职务",],
        unit_examples=["人", "名"],
    ),
    q_field(
        "independent_directors",
        "独立董事人数",
        "G",
        "number",
        "person_count",
        aliases=["独立董事人数", "独立董事数量","独董人数"],
        required_any=["独立董事人数", "独立董事数量","独董人数"],
        forbidden_any=["独立董事比例", "独立董事占比", "%"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "independent_director_ratio",
        "独立董事比例",
        "G",
        "percentage",
        "percentage",
        aliases=["独立董事比例", "独立董事占比"],
        required_any=["独立董事比例", "独立董事占比"],
        forbidden_any=["独立董事人数", "独立董事数量"],
        unit_examples=["%"],
    ),
    q_field(
        "female_directors",
        "女性董事人数",
        "G",
        "number",
        "person_count",
        aliases=["女性董事人数", "女性董事数量"],
        required_any=["女性董事人数", "女性董事数量"],
        forbidden_any=["女性董事比例", "女性董事占比", "%"],
        unit_examples=["人", "名"],
    ),
    q_field(
        "board_meetings",
        "董事会会议次数",
        "G",
        "number",
        "count",
        aliases=["董事会会议次数", "董事会召开次数", "董事会次数", "董事会会议召开次数"],
        required_any=["董事会会议", "董事会召开"],
        forbidden_any=["股东大会", "监事会", "审议", "议案"],
        unit_examples=["次"],
    ),
    q_field(
        "shareholder_meetings",
        "股东大会会议次数",
        "G",
        "number",
        "count",
        aliases=["股东大会召开次数", "股东大会会议次数", "股东大会次数", "股东大会会议召开次数"],
        required_any=["股东大会"],
        forbidden_any=["董事会", "监事会", "审议", "议案"],
        unit_examples=["次"],
    ),
    q_field(
        "anti_corruption_training_sessions",
        "反腐败培训次数",
        "G",
        "number",
        "count",
        aliases=["反腐败培训次数", "反贪污培训次数", "廉洁培训次数", "反商业贿赂培训次数"],
        required_any=["反腐败培训", "反贪污培训", "廉洁培训", "反商业贿赂培训"],
        forbidden_any=["参与人数", "培训人数", "培训人次", "培训时数", "培训总时长", "小时", "学时", "%", "百分比"],
        unit_examples=["次", "场次"],
    ),
    q_field(
        "anti_corruption_training_participants",
        "反腐败培训参与人数或人次",
        "G",
        "number",
        "person_time",
        aliases=[
            "反腐败培训参与人数",
            "反腐败培训人次",
            "反贪污培训人次",
            "员工反腐败培训人次",
            "管理人员反腐败培训人次",
            "参加反商业贿赂及反贪污培训的员工人数",
            "参加反商业贿赂及反贪污培训的董事及高级管理人员人数",
        ],
        required_any=["反腐败培训", "反贪污培训", "反商业贿赂", "廉洁培训"],
        forbidden_any=["培训次数", "培训时数", "培训总时长", "培训小时", "平均时长", "覆盖率", "百分比", "%", "占比"],
        unit_examples=["人", "人次"],
    ),
    q_field(
        "anti_corruption_training_hours",
        "反腐败培训总时长",
        "G",
        "number",
        "hour",
        aliases=[
            "反腐败培训时数",
            "反腐败培训总时长",
            "反腐败培训小时数",
            "反贪污培训时数",
            "反商业贿赂培训时数",
            "员工反腐败培训时数",
            "管理人员反腐败培训时数",
            "反商业贿赂及反贪污培训总时长",
            "提供的反商业贿赂及反贪污培训总时长",
            "向董事及高级管理人员提供的反商业贿赂及反贪污培训总时长",
        ],
        required_any=["反腐败培训", "反贪污培训", "反商业贿赂", "廉洁培训"],
        forbidden_any=["培训次数", "培训人次", "培训人数", "覆盖率", "百分比", "%", "平均"],
        unit_examples=["小时", "学时"],
    ),
    q_field(
        "confirmed_corruption_cases",
        "确认的腐败事件数量",
        "G",
        "number",
        "count",
        aliases=["确认的腐败事件数量", "腐败事件数量", "贪腐事件数量", "已确认腐败事件"],
        required_any=["确认", "腐败事件", "贪腐事件"],
        forbidden_any=["培训", "举报"],
        unit_examples=["件", "起", "次"],
    ),
    q_field(
        "whistleblowing_cases",
        "举报案件数量",
        "G",
        "number",
        "count",
        aliases=["举报案件数量", "投诉举报案件数量", "申诉案件数量", "举报数量", "反贪污腐败举报事件总数", "举报事件总数"],
        required_any=["举报案件", "投诉举报", "申诉案件", "举报数量", "举报事件"],
        forbidden_any=["客户投诉", "举报机制", "举报渠道"],
        unit_examples=["件", "起", "次"],
    ),
    q_field(
        "patent_applications_new",
        "当年申请专利数量",
        "S",
        "number",
        "count",
        aliases=["申报专利数","专利申请数","专利申请数量","申请专利数量","当年申请专利数量","报告当年申请的专利总数","新增专利申请数","报告期内发明专利的申请数","发明专利申请数"],
        required_any=["申报专利", "专利申请", "申请专利", "专利申请数","报告当年申请","报告期内发明专利的申请数","发明专利的申请数","发明专利申请数"],
        forbidden_any=["授权", "累计", "有效专利"],
        unit_examples=["项", "件", "个"],
    ),

    # =====================================================
    # 定性机制类：5 个，主要走路线 B 正文 RAG
    # =====================================================
    t_field(
        "board_esg_oversight",
        "董事会 ESG 监督机制",
        "G",
        aliases=["董事会ESG监督", "董事会可持续发展监督", "董事会审议ESG", "董事会参与ESG管理"],
        required_any=["董事会", "ESG", "可持续发展"],
    ),
    t_field(
        "esg_committee",
        "ESG 委员会或可持续发展委员会",
        "G",
        aliases=["ESG委员会", "可持续发展委员会", "社会责任委员会", "ESG工作小组"],
        required_any=["ESG委员会", "可持续发展委员会", "社会责任委员会", "ESG工作小组"],
    ),
    t_field(
        "anti_corruption_policy",
        "反腐败政策",
        "G",
        aliases=["反腐败政策", "反贪污政策", "反商业贿赂制度", "廉洁从业制度", "商业道德政策"],
        required_any=["反腐败", "反贪污", "反商业贿赂", "廉洁", "商业道德"],
    ),
    t_field(
        "whistleblowing_mechanism",
        "举报机制",
        "G",
        aliases=["举报机制", "举报渠道", "投诉机制", "申诉机制", "举报邮箱", "举报热线"],
        required_any=["举报机制", "举报渠道", "投诉机制", "申诉机制", "举报邮箱", "举报热线"],
    ),
    t_field(
        "supplier_esg_assessment",
        "供应商 ESG 评估机制",
        "S",
        aliases=["供应商ESG评估", "供应商环境社会评估", "供应商可持续发展评估", "供应商社会责任评估", "供应商审核", "供应商评价"],
        required_any=["供应商", "ESG", "环境社会", "可持续", "社会责任", "审核", "评价"],
    ),
]


ESG_SCHEMA = {item["field_key"]: item for item in CORE_SCHEMA}
ESG_FIELD_KEYS = list(ESG_SCHEMA.keys())

NUMERIC_FIELD_KEYS = [
    item["field_key"]
    for item in CORE_SCHEMA
    if item["indicator_type"] == "quantitative"
]

TEXT_FIELD_KEYS = [
    item["field_key"]
    for item in CORE_SCHEMA
    if item["indicator_type"] == "qualitative"
]


SCHEMA_ITEMS = [
    (
        item["field_key"],
        item["name_cn"] + " / " + " / ".join(item.get("aliases", [])),
        item["category"],
        item["value_type"],
        item["preferred_source"],
        item["unit_required"],
        item["year_required"],
    )
    for item in CORE_SCHEMA
]


def get_schema_item(field_key: str) -> Dict[str, Any]:
    return ESG_SCHEMA.get(field_key, {})


def get_aliases(field_key: str) -> List[str]:
    item = ESG_SCHEMA.get(field_key, {})
    return item.get("aliases", [])


def get_unit_examples(field_key: str) -> List[str]:
    item = ESG_SCHEMA.get(field_key, {})
    return item.get("unit_examples", [])


def get_core_schema_prompt_text() -> str:
    """
    给 qwen-plus 做指标匹配 / unknown 指标分析时使用。
    """
    lines = []

    for item in CORE_SCHEMA:
        aliases = "、".join(item.get("aliases", []))
        units = "、".join(item.get("unit_examples", []))
        required_any = "、".join(item.get("required_any", []))
        forbidden_any = "、".join(item.get("forbidden_any", []))

        line = (
            f"- field_key: {item['field_key']}\n"
            f"  name_cn: {item['name_cn']}\n"
            f"  category: {item['category']}\n"
            f"  indicator_type: {item['indicator_type']}\n"
            f"  value_type: {item['value_type']}\n"
            f"  unit_type: {item.get('unit_type', '')}\n"
            f"  aliases: {aliases}\n"
            f"  unit_examples: {units}\n"
            f"  required_any: {required_any}\n"
            f"  forbidden_any: {forbidden_any}"
        )
        lines.append(line)

    return "\n".join(lines)


def schema_summary() -> Dict[str, int]:
    return {
        "total": len(CORE_SCHEMA),
        "quantitative": len(NUMERIC_FIELD_KEYS),
        "qualitative": len(TEXT_FIELD_KEYS),
        "E": sum(1 for item in CORE_SCHEMA if item["category"] == "E"),
        "S": sum(1 for item in CORE_SCHEMA if item["category"] == "S"),
        "G": sum(1 for item in CORE_SCHEMA if item["category"] == "G"),
    }


if __name__ == "__main__":
    summary = schema_summary()
    print(f"Core ESG Schema 指标数量: {summary['total']}")
    print(f"定量指标数量: {summary['quantitative']}")
    print(f"定性指标数量: {summary['qualitative']}")
    print(f"E 指标数量: {summary['E']}")
    print(f"S 指标数量: {summary['S']}")
    print(f"G 指标数量: {summary['G']}")
